export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just For You",
    description:
      "Get interview questions and model answers based on your role. and specific area of focus.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Answer only the when you're ready, Dive deeper into any concept instantly with AI-powered details explanations.",
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any questions and pin important questions to the top.",
  },
  {
    id: "04",
    title: "Understand The 'Why' Behind Answers",
    description:
      "Beyond Just Answers, Unlock detailed concepts explanation generated by AI.",
  },
  {
    id: "05",
    title: "Save Organize And Revisit",
    description:
      "Easily save Your interview sets, organize them neatly in your dashboard and revisit any time.",
  },
];
