import {
  BookOpenCheck,
  Crosshair,
  Save,
  Search,
  SquarePen,
} from "lucide-react";

export function fromDate(date: Date) {
  return date.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just For You",
    icon: Crosshair,
    description:
      "Get interview questions and model answers based on your role. and specific area of focus.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    icon: BookOpenCheck,
    description:
      "Answer only the when you're ready, Dive deeper into any concept instantly with AI-powered details explanations.",
  },
  {
    id: "03",
    icon: SquarePen,
    title: "Capture Your Insights",
    description:
      "Add personal notes to any questions and pin important questions to the top.",
  },
  {
    id: "04",
    icon: Search,
    title: "Understand The 'Why' Behind Answers",
    description:
      "Beyond Just Answers, Unlock detailed concepts explanation generated by AI.",
  },
  {
    id: "05",
    icon: Save,
    title: "Save Organize And Revisit",
    description:
      "Easily save Your interview sets, organize them neatly in your dashboard and revisit any time.",
  },
];

export const TESTIMONIALS = [
  {
    name: "John Doe",
    rating: 5,
    img: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=200&h=200&auto=format&fit=crop",
    review:
      "I was skeptical about the AI-powered interview prep tool but after using it, I'm hooked! It's so easy to prepare for interviews and I've been able to land my dream job. Highly recommended!",
  },
  {
    name: "Mark Smith",
    rating: 5,
    img: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?q=80&w=200&h=200&auto=format&fit=crop",
    review:
      "The AI-generated questions and explanations were spot-on and made the interview process so much easier. I couldn't have done it without this tool. Highly satisfied!",
  },
  {
    name: "Alice Johnson",
    rating: 5,
    img: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=200&h=200&auto=format&fit=crop",
    review:
      "I was a bit nervous about the AI-generated questions but they were so easy to understand. The explanations were clear and helpful. I was able to ace the interview and land my dream job.",
  },
];
